name: Deploy_via_ftp
on: push
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: FTP Deploy Locaweb
      uses: locaweb/ftp-deploy@1.0.0
      with:
        host: ${{ secrets.FTP_DEPLOY_HOST }} 
        user: ${{ secrets.FTP_DEPLOY_USER }}
        password: ${{ secrets.FTP_DEPLOY_SENHA }}
